name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  
  workflow_dispatch:


  
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Install Libs
        run: |
          sudo apt-get update
          sudo apt-get install libhdf5-dev
          sudo apt-get install --reinstall libxcb-xinerama0
          sudo apt-get install qtbase5-dev
      - uses: actions/checkout@v5
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
      - uses: julia-actions/cache@v2
      - name: Install docs dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.develop([PackageSpec(path=pwd()), PackageSpec(url="https://github.com/ptiede/ComradeBase.jl")]); Pkg.instantiate()'
      - name: Build Tutorials
        run: julia --project=docs -e 'include(joinpath(pwd(), "docs", "tutorials.jl"))'
      - name: Build and deploy docs
        uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          GKSwstype: "100" # for Plots.jl plots (if you have them)
          JULIA_DEBUG: "Documenter"
          DATADEPS_ALWAYS_ACCEPT: true
